### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by wangxiyuan** [ververica/frocksdb#14]
[Rocksdb 6.4.6](https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni/6.4.6) release now contains `librocksdbjni-linux-aarch64.so` for aarch64 platform. It's good for frocksdb to support it as well.

It's very easy to build the aarch64 package on an ARM machine:
```
export DEBUG_LEVEL=0 && make rocksdbjava
```
[OpenLab](https://openlabtesting.org/) community can donate ARM machine for frocksdb team to help build and release ARM package to maven center. Please let me know if you need one.

**Comment by carp84** [comment]
Thanks for bringing up the discussion @wangxiyuan 

Due to the issue of [rocksdb 5774](https://github.com/facebook/rocksdb/issues/5774), we cannot bump our frocksdb version to the latest version but need to stay on 5.17.2. Have you tried whether it's possible to build 5.17.2 on ARM? Thanks.

**Comment by wangxiyuan** [comment]
@carp84 Yeah, I know frocksdb should use 5.17.2. And it's easy to build 5.17.2 on ARM. 
Maybe you know that now I send the Flink test result on aarch64 everyday through builds@flink.apache.org mailist[1].  Acutally these job runs under a pre-built ARM frocksdb[2,3]. So it's fully tested with Flink unit test and e2e test.

And of cause I can provide a free VM machine for upstream to build and release the aarch64 package.

1:  http://mail-archives.apache.org/mod_mbox/flink-builds/201912.mbox/browser
2:  https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/flink-end-to-end-test/build_and_test_core_and_tests.yaml#L10-L21
3. https://github.com/theopenlab/openlab-zuul-jobs/tree/master/playbooks/flink-end-to-end-test

**Comment by wangxiyuan** [comment]
https://issues.apache.org/jira/browse/FLINK-13598 for discusstion.

**Comment by Myasuka** [comment]
@wangxiyuan As we are ready to bump RocksDB version to 6.11+, and we're facing the problem of releasing on ARM platform. Do you have resource/virtual machine to release those arm related binary `.so`?

**Comment by wangxiyuan** [comment]
@Myasuka Yeah, you can request an arm vm at https://www.linaro.cloud/ for longer usage or openlab can provide you an arm vm for temp usage.

If you need the machine from openlab, please open an issue here: https://github.com/theopenlab/openlab with `Test Request`. I'll provide one for you ASAP.

**Comment by Myasuka** [comment]
@wangxiyuan Thanks for your warm help. I've created the issue https://github.com/theopenlab/openlab/issues/614
