### ISSUE TITLE
frocksdb 6.10 usage

### ISSUE THREAD

**Issue by zhougit86** [ververica/frocksdb#24]
I need to use the FIFO compation, and there is a configuration:    compactionOptionsFIFO.setAllowCompaction, which is only available in 
https://mvnrepository.com/artifact/io.github.myasuka/frocksdbjni 6.10 + version 
I noticed there is a performance issue,  https://github.com/facebook/rocksdb/issues/5774
If I am not so concerned about performance, can I use it in my own job (flink 1.11)

**Comment by Myasuka** [comment]
Flink adopts RocksDB's compaction filter to work for TTL, however, Flink implemented [compaction filter](https://github.com/ververica/frocksdb/blob/FRocksDB-5.17.2/utilities/flink/flink_compaction_filter.cc) is not included in default RocksDB repo. This is the main difference.
