### ISSUE TITLE
is frocksdb support store on hdfs?

### ISSUE THREAD

**Issue by hameizi** [ververica/frocksdb#41]
I want store rocksdb data  on hdfs, but i found rocksdb don't support on hdfs(https://github.com/facebook/rocksdb/issues/9067). So i want konw is frocksdb support store on hdfs? Because flink rocksdbStateBackend is store data on hdfs.

**Comment by Myasuka** [comment]
Hi @hameizi, I think you misunderstood the relationship between `RocksDBStateBackend` with HDFS checkpointed path. From Flink-1.13, Flink has decoupled the concept of state backend and checkpoints (please refer to [state_backends](https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/ops/state/state_backends/) and [checkpoint_storage](https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/ops/state/checkpoints/)). 

Flink does not depend on internal state store to support backup on HDFS, it actually leverages RocksDB to serve state access and uploads local checkpoints to remote DFS via Flink. In other words, there is no need for FrocksDB to support HDFS.

**Comment by hameizi** [comment]
@Myasuka Thanks , i get.
